export const GM_FAMILIES = {
  Piano: { label: 'Piano', range: [0, 7] },
  'Chromatic Percussion': { label: 'Chromatic Percussion', range: [8, 15] },
  Organ: { label: 'Organ', range: [16, 23] },
  Guitar: { label: 'Guitar', range: [24, 31] },
  Bass: { label: 'Bass', range: [32, 39] },
  Strings: { label: 'Strings', range: [40, 47] },
  Ensemble: { label: 'Ensemble', range: [48, 55] },
  Brass: { label: 'Brass', range: [56, 63] },
  Reed: { label: 'Reed', range: [64, 71] },
  Pipe: { label: 'Pipe', range: [72, 79] },
  'Synth Lead': { label: 'Synth Lead', range: [80, 87] },
  'Synth Pad': { label: 'Synth Pad', range: [88, 95] },
  'Synth FX': { label: 'Synth FX', range: [96, 103] },
  Ethnic: { label: 'Ethnic', range: [104, 111] },
  Percussive: { label: 'Percussive', range: [112, 119] },
  'Sound Effects': { label: 'Sound Effects', range: [120, 127] }
};

const GM_PROGRAM_NAMES = [
  'Acoustic Grand Piano',
  'Bright Acoustic Piano',
  'Electric Grand Piano',
  'Honky-tonk Piano',
  'Electric Piano 1',
  'Electric Piano 2',
  'Harpsichord',
  'Clavinet',
  'Celesta',
  'Glockenspiel',
  'Music Box',
  'Vibraphone',
  'Marimba',
  'Xylophone',
  'Tubular Bells',
  'Dulcimer',
  'Drawbar Organ',
  'Percussive Organ',
  'Rock Organ',
  'Church Organ',
  'Reed Organ',
  'Accordion',
  'Harmonica',
  'Tango Accordion',
  'Acoustic Guitar (nylon)',
  'Acoustic Guitar (steel)',
  'Electric Guitar (jazz)',
  'Electric Guitar (clean)',
  'Electric Guitar (muted)',
  'Overdriven Guitar',
  'Distortion Guitar',
  'Guitar Harmonics',
  'Acoustic Bass',
  'Electric Bass (finger)',
  'Electric Bass (pick)',
  'Fretless Bass',
  'Slap Bass 1',
  'Slap Bass 2',
  'Synth Bass 1',
  'Synth Bass 2',
  'Violin',
  'Viola',
  'Cello',
  'Contrabass',
  'Tremolo Strings',
  'Pizzicato Strings',
  'Orchestral Harp',
  'Timpani',
  'String Ensemble 1',
  'String Ensemble 2',
  'Synth Strings 1',
  'Synth Strings 2',
  'Choir Aahs',
  'Voice Oohs',
  'Synth Voice',
  'Orchestra Hit',
  'Trumpet',
  'Trombone',
  'Tuba',
  'Muted Trumpet',
  'French Horn',
  'Brass Section',
  'Synth Brass 1',
  'Synth Brass 2',
  'Soprano Sax',
  'Alto Sax',
  'Tenor Sax',
  'Baritone Sax',
  'Oboe',
  'English Horn',
  'Bassoon',
  'Clarinet',
  'Piccolo',
  'Flute',
  'Recorder',
  'Pan Flute',
  'Blown Bottle',
  'Shakuhachi',
  'Whistle',
  'Ocarina',
  'Lead 1 (square)',
  'Lead 2 (sawtooth)',
  'Lead 3 (calliope)',
  'Lead 4 (chiff)',
  'Lead 5 (charang)',
  'Lead 6 (voice)',
  'Lead 7 (fifths)',
  'Lead 8 (bass + lead)',
  'Pad 1 (new age)',
  'Pad 2 (warm)',
  'Pad 3 (polysynth)',
  'Pad 4 (choir)',
  'Pad 5 (bowed)',
  'Pad 6 (metallic)',
  'Pad 7 (halo)',
  'Pad 8 (sweep)',
  'FX 1 (rain)',
  'FX 2 (soundtrack)',
  'FX 3 (crystal)',
  'FX 4 (atmosphere)',
  'FX 5 (brightness)',
  'FX 6 (goblins)',
  'FX 7 (echoes)',
  'FX 8 (sci-fi)',
  'Sitar',
  'Banjo',
  'Shamisen',
  'Koto',
  'Kalimba',
  'Bag pipe',
  'Fiddle',
  'Shanai',
  'Tinkle Bell',
  'Agogo',
  'Steel Drums',
  'Woodblock',
  'Taiko Drum',
  'Melodic Tom',
  'Synth Drum',
  'Reverse Cymbal',
  'Guitar Fret Noise',
  'Breath Noise',
  'Seashore',
  'Bird Tweet',
  'Telephone Ring',
  'Helicopter',
  'Applause',
  'Gunshot'
];

export const GM_SOUNDFONT_NAMES = [
  'acoustic_grand_piano',
  'bright_acoustic_piano',
  'electric_grand_piano',
  'honkytonk_piano',
  'electric_piano_1',
  'electric_piano_2',
  'harpsichord',
  'clavinet',
  'celesta',
  'glockenspiel',
  'music_box',
  'vibraphone',
  'marimba',
  'xylophone',
  'tubular_bells',
  'dulcimer',
  'drawbar_organ',
  'percussive_organ',
  'rock_organ',
  'church_organ',
  'reed_organ',
  'accordion',
  'harmonica',
  'tango_accordion',
  'acoustic_guitar_nylon',
  'acoustic_guitar_steel',
  'electric_guitar_jazz',
  'electric_guitar_clean',
  'electric_guitar_muted',
  'overdriven_guitar',
  'distortion_guitar',
  'guitar_harmonics',
  'acoustic_bass',
  'electric_bass_finger',
  'electric_bass_pick',
  'fretless_bass',
  'slap_bass_1',
  'slap_bass_2',
  'synth_bass_1',
  'synth_bass_2',
  'violin',
  'viola',
  'cello',
  'contrabass',
  'tremolo_strings',
  'pizzicato_strings',
  'orchestral_harp',
  'timpani',
  'string_ensemble_1',
  'string_ensemble_2',
  'synth_strings_1',
  'synth_strings_2',
  'choir_aahs',
  'voice_oohs',
  'synth_voice',
  'orchestra_hit',
  'trumpet',
  'trombone',
  'tuba',
  'muted_trumpet',
  'french_horn',
  'brass_section',
  'synth_brass_1',
  'synth_brass_2',
  'soprano_sax',
  'alto_sax',
  'tenor_sax',
  'baritone_sax',
  'oboe',
  'english_horn',
  'bassoon',
  'clarinet',
  'piccolo',
  'flute',
  'recorder',
  'pan_flute',
  'blown_bottle',
  'shakuhachi',
  'whistle',
  'ocarina',
  'lead_1_square',
  'lead_2_sawtooth',
  'lead_3_calliope',
  'lead_4_chiff',
  'lead_5_charang',
  'lead_6_voice',
  'lead_7_fifths',
  'lead_8_bass__lead',
  'pad_1_new_age',
  'pad_2_warm',
  'pad_3_polysynth',
  'pad_4_choir',
  'pad_5_bowed',
  'pad_6_metallic',
  'pad_7_halo',
  'pad_8_sweep',
  'fx_1_rain',
  'fx_2_soundtrack',
  'fx_3_crystal',
  'fx_4_atmosphere',
  'fx_5_brightness',
  'fx_6_goblins',
  'fx_7_echoes',
  'fx_8_sci_fi',
  'sitar',
  'banjo',
  'shamisen',
  'koto',
  'kalimba',
  'bagpipe',
  'fiddle',
  'shanai',
  'tinkle_bell',
  'agogo',
  'steel_drums',
  'woodblock',
  'taiko_drum',
  'melodic_tom',
  'synth_drum',
  'reverse_cymbal',
  'guitar_fret_noise',
  'breath_noise',
  'seashore',
  'bird_tweet',
  'telephone_ring',
  'helicopter',
  'applause',
  'gunshot'
];

const resolveFamily = (program) => {
  const entry = Object.values(GM_FAMILIES).find((family) => program >= family.range[0] && program <= family.range[1]);
  return entry?.label || 'Unknown';
};

export const GM_PROGRAMS = GM_PROGRAM_NAMES.map((name, program) => ({
  program,
  name,
  family: resolveFamily(program)
}));

export const GM_DRUM_ROWS = [
  { label: 'Kick', pitch: 36 },
  { label: 'Snare', pitch: 38 },
  { label: 'Closed Hat', pitch: 42 },
  { label: 'Open Hat', pitch: 46 },
  { label: 'Low Tom', pitch: 45 },
  { label: 'Mid Tom', pitch: 47 },
  { label: 'High Tom', pitch: 50 },
  { label: 'Crash', pitch: 49 },
  { label: 'Ride', pitch: 51 }
];

export const GM_DRUMS = [
  { pitch: 35, label: 'Acoustic Bass Drum' },
  { pitch: 36, label: 'Bass Drum 1' },
  { pitch: 37, label: 'Side Stick' },
  { pitch: 38, label: 'Acoustic Snare' },
  { pitch: 39, label: 'Hand Clap' },
  { pitch: 40, label: 'Electric Snare' },
  { pitch: 41, label: 'Low Floor Tom' },
  { pitch: 42, label: 'Closed Hi-Hat' },
  { pitch: 43, label: 'High Floor Tom' },
  { pitch: 44, label: 'Pedal Hi-Hat' },
  { pitch: 45, label: 'Low Tom' },
  { pitch: 46, label: 'Open Hi-Hat' },
  { pitch: 47, label: 'Low-Mid Tom' },
  { pitch: 48, label: 'Hi-Mid Tom' },
  { pitch: 49, label: 'Crash Cymbal 1' },
  { pitch: 50, label: 'High Tom' },
  { pitch: 51, label: 'Ride Cymbal 1' },
  { pitch: 52, label: 'Chinese Cymbal' },
  { pitch: 53, label: 'Ride Bell' },
  { pitch: 54, label: 'Tambourine' },
  { pitch: 55, label: 'Splash Cymbal' },
  { pitch: 56, label: 'Cowbell' },
  { pitch: 57, label: 'Crash Cymbal 2' },
  { pitch: 58, label: 'Vibra Slap' },
  { pitch: 59, label: 'Ride Cymbal 2' },
  { pitch: 60, label: 'Hi Bongo' },
  { pitch: 61, label: 'Low Bongo' },
  { pitch: 62, label: 'Mute Hi Conga' },
  { pitch: 63, label: 'Open Hi Conga' },
  { pitch: 64, label: 'Low Conga' },
  { pitch: 65, label: 'High Timbale' },
  { pitch: 66, label: 'Low Timbale' },
  { pitch: 67, label: 'High Agogo' },
  { pitch: 68, label: 'Low Agogo' },
  { pitch: 69, label: 'Cabasa' },
  { pitch: 70, label: 'Maracas' },
  { pitch: 71, label: 'Short Whistle' },
  { pitch: 72, label: 'Long Whistle' },
  { pitch: 73, label: 'Short Guiro' },
  { pitch: 74, label: 'Long Guiro' },
  { pitch: 75, label: 'Claves' },
  { pitch: 76, label: 'Hi Wood Block' },
  { pitch: 77, label: 'Low Wood Block' },
  { pitch: 78, label: 'Mute Cuica' },
  { pitch: 79, label: 'Open Cuica' },
  { pitch: 80, label: 'Mute Triangle' },
  { pitch: 81, label: 'Open Triangle' }
];

export const GM_DRUM_KITS = [
  { id: 'standard', label: 'Standard Kit', bankMSB: 0, bankLSB: 0, program: 0, soundfont: 'standard_kit' },
  { id: 'room', label: 'Room Kit', bankMSB: 0, bankLSB: 0, program: 1, soundfont: 'room_kit' },
  { id: 'power', label: 'Power Kit', bankMSB: 0, bankLSB: 0, program: 2, soundfont: 'power_kit' },
  { id: 'electronic', label: 'Electronic Kit', bankMSB: 0, bankLSB: 0, program: 3, soundfont: 'electronic_kit' },
  { id: 'jazz', label: 'Jazz Kit', bankMSB: 0, bankLSB: 0, program: 4, soundfont: 'jazz_kit' },
  { id: 'brush', label: 'Brush Kit', bankMSB: 0, bankLSB: 0, program: 5, soundfont: 'brush_kit' },
  { id: 'orchestra', label: 'Orchestra Kit', bankMSB: 0, bankLSB: 0, program: 6, soundfont: 'orchestra_kit' },
  { id: 'sfx', label: 'SFX Kit', bankMSB: 0, bankLSB: 0, program: 7, soundfont: 'sfx_kit' }
];

export const isDrumChannel = (channel) => channel === 9;

export const formatProgramNumber = (program) => `${String(program + 1).padStart(3, '0')}`;
