export const LEGEND = {
  player: { label: 'Player', glyph: 'P', minimap: '◎' },
  skitter: { label: 'Skitter', glyph: 'SK', minimap: '✦' },
  spitter: { label: 'Spitter', glyph: 'SP', minimap: '✧' },
  bulwark: { label: 'Bulwark', glyph: 'BW', minimap: '■' },
  floater: { label: 'Floater', glyph: 'FL', minimap: '○' },
  drifter: { label: 'Drifter', glyph: 'DF', minimap: '◌' },
  bobber: { label: 'Bobber', glyph: 'BB', minimap: '◎' },
  harrier: { label: 'Harrier', glyph: 'HR', minimap: '❂' },
  slicer: { label: 'Slicer', glyph: 'SL', minimap: '◇' },
  hivenode: { label: 'Hive Node', glyph: 'HN', minimap: '▣' },
  bouncer: { label: 'Bouncer', glyph: 'BO', minimap: '◍' },
  pouncer: { label: 'Pouncer', glyph: 'PN', minimap: '◒' },
  coward: { label: 'Coward', glyph: 'CW', minimap: '◐' },
  ranger: { label: 'Ranger', glyph: 'RG', minimap: '◑' },
  sentinel: { label: 'Sentinel', glyph: 'SE', minimap: '✶' },
  finalboss: { label: 'Rift Tyrant', glyph: 'RT', minimap: '✹' },
  sunderbehemoth: { label: 'Sunder Behemoth', glyph: 'SB', minimap: '✖' },
  riftram: { label: 'Rift Ram', glyph: 'RR', minimap: '✖' },
  broodtitan: { label: 'Brood Titan', glyph: 'BT', minimap: '✖' },
  nullaegis: { label: 'Null Aegis', glyph: 'NA', minimap: '✖' },
  hexmatron: { label: 'Hex Matron', glyph: 'HM', minimap: '✖' },
  gravewarden: { label: 'Grave Warden', glyph: 'GW', minimap: '✖' },
  obsidiancrown: { label: 'Obsidian Crown', glyph: 'OC', minimap: '✖' },
  cataclysmcolossus: { label: 'Cataclysm Colossus', glyph: 'CC', minimap: '✖' },
  ability: { label: 'Ability Cache', glyph: '⚙', minimap: '⬡' },
  vitality: { label: 'Vitality Core', glyph: 'HP', minimap: '✚' },
  save: { label: 'Save Node', glyph: 'SV', minimap: '⬟' },
  shop: { label: 'Shop', glyph: '$', minimap: '▵' },
  anchor: { label: 'Anchor Socket', glyph: '⚓', minimap: '⊙' },
  wood: { label: 'Wood Barricade', glyph: 'W', minimap: 'W' },
  woodBox: { label: 'Wooden Box', glyph: 'Y', minimap: 'Y' },
  metal: { label: 'Welded Metal', glyph: 'X', minimap: 'X' },
  brittle: { label: 'Brittle Wall', glyph: 'C', minimap: 'C' },
  debris: { label: 'Heavy Debris', glyph: 'U', minimap: 'U' },
  snow: { label: 'Snow Block', glyph: 'N', minimap: 'N' },
  lead: { label: 'Lead Block', glyph: 'P', minimap: 'P' },
  switch: { label: 'Counterweight Switch', glyph: 'T', minimap: 'T' },
  bossGate: { label: 'Rift Seal', glyph: 'B', minimap: 'B' },
  objective: { label: 'Objective', glyph: '◈', minimap: '◈' },
  loot: { label: 'Loot', glyph: '✪', minimap: '✪' }
};
