export const LEGEND = {
  player: { label: 'Player', glyph: 'P', minimap: '◎' },
  skitter: { label: 'Skitter', glyph: 'SK', minimap: '✦' },
  spitter: { label: 'Spitter', glyph: 'SP', minimap: '✧' },
  bulwark: { label: 'Bulwark', glyph: 'BW', minimap: '■' },
  floater: { label: 'Floater', glyph: 'FL', minimap: '○' },
  slicer: { label: 'Slicer', glyph: 'SL', minimap: '◇' },
  hivenode: { label: 'Hive Node', glyph: 'HN', minimap: '▣' },
  sentinel: { label: 'Sentinel', glyph: 'SE', minimap: '✶' },
  finalboss: { label: 'Rift Tyrant', glyph: 'RT', minimap: '✹' },
  ability: { label: 'Ability Cache', glyph: '⚙', minimap: '⬡' },
  vitality: { label: 'Vitality Core', glyph: 'HP', minimap: '✚' },
  save: { label: 'Save Node', glyph: 'SV', minimap: '⬟' },
  shop: { label: 'Shop', glyph: '$', minimap: '▵' },
  anchor: { label: 'Anchor Socket', glyph: '⚓', minimap: '⊙' },
  wood: { label: 'Wood Barricade', glyph: 'W', minimap: 'W' },
  metal: { label: 'Welded Metal', glyph: 'X', minimap: 'X' },
  brittle: { label: 'Brittle Wall', glyph: 'C', minimap: 'C' },
  debris: { label: 'Heavy Debris', glyph: 'U', minimap: 'U' },
  switch: { label: 'Counterweight Switch', glyph: 'T', minimap: 'T' },
  bossGate: { label: 'Rift Seal', glyph: 'B', minimap: 'B' },
  objective: { label: 'Objective', glyph: '◈', minimap: '◈' },
  loot: { label: 'Loot', glyph: '✪', minimap: '✪' }
};
