export const INPUT_ACTIONS = {
  NAV_UP: 'NAV_UP',
  NAV_DOWN: 'NAV_DOWN',
  NAV_LEFT: 'NAV_LEFT',
  NAV_RIGHT: 'NAV_RIGHT',
  CONFIRM: 'CONFIRM',
  CANCEL: 'CANCEL',
  DRAW_PRESS: 'DRAW_PRESS',
  DRAW_RELEASE: 'DRAW_RELEASE',
  SET_TOOL: 'SET_TOOL',
  PAN_XY: 'PAN_XY',
  UNDO: 'UNDO',
  REDO: 'REDO',
  PANEL_PREV: 'PANEL_PREV',
  PANEL_NEXT: 'PANEL_NEXT',
  QUICK_COLOR: 'QUICK_COLOR',
  QUICK_TOOL: 'QUICK_TOOL',
  TOGGLE_UI_MODE: 'TOGGLE_UI_MODE',
  TOGGLE_MODE: 'TOGGLE_MODE',
  ERASE_PRESS: 'ERASE_PRESS',
  ERASE_RELEASE: 'ERASE_RELEASE',
  MENU: 'MENU'
};

export const NAV_REPEAT_DELAY = 0.18;
export const TRIGGER_THRESHOLD = 0.6;
